name: Deployment
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Echo location
        run: pwd
      - name: Get code
        uses: actions/checkout@v4
      - name: Show files
        run: pwd  
      - name: Load and cache dependencies
        id: cache-deps
        uses: ./.github/actions/cached-deps # Using the custom composite action
        with:
          caching: 'false'  # Disable caching as part of the composite action inputs
      - name: Output info # Output from composite action
        run: echo "Cache used? ${{ steps.cache-deps.outputs.used-cache }}"   
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load and cache dependencies
        uses: ./.github/actions/cached-deps # Using the custom composite action
      - name: Test code
        id: run-tests
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load and cache dependencies
        uses: ./.github/actions/cached-deps # Using the custom composite action
      - name: Build website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist
      - name: Output contents
        run: ls
      - name: Deploy site
        uses: ./.github/actions/deploy-s3-javascript # Using the custom JavaScript action to deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}       # AWS credentials from repository secrets
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # AWS credentials from repository secrets
        with:
          bucket: 'test-gha-custon-action-bucket '  # Replace with your S3 bucket name
          bucket-region: 'eu-north-1'   # Replace with your S3 bucket region if different
          dist-folder: './dist'        # Folder containing built website files
  # information: # Job to demonstrate usage of JavaScript custom action
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get code # must checkout code to use local custom action
  #       uses: actions/checkout@v4
  #     - name: Run JS custom actions
  #       uses: ./.github/actions/deploy-s3-javascript # Using the custom JavaScript action